---
 - hosts: worker
   gather_facts: no
   remote_user: ec2-user
   become: true
   tasks:
    - name: Install the latest docker
      yum:
       name: docker
       state: latest             
    - name: ensure docker is running
      service:
        name: docker
        state: started
               
    handlers:
    - name:  restart docker
      service:
        name: docker
        state: restarted
               
            


    
